### ISSUE TITLE
NRST/RESET line doesn't require a pull-up resistor

### ISSUE THREAD

**Issue by stuartpittaway** [opulo-inc/feeder#25]
# Version Number
What is the latest known version number where this issue is present?

# Bugfix or Enhancement
potential enhancement

# Description
Resistor R4 (10K) is a pull up on the RESET line - this doesn't appear to be required according to the datasheet.

Page 69 of datasheet - NRST pin characteristics
```
The NRST pin input driver uses the CMOS technology. It is connected to a permanent pullup resistor, RPU
```

# Suggested Solution
Remove R4

**Comment by sphawes** [comment]
Thanks for the issue @stuartpittaway! We originally followed the datasheet and didn't have that resistor, but we found that it was too weak. In some feeders, when the peel motor would power on it would lightly couple to the reset trace and cause a reset. Adding a stronger external pullup fixed the issue!
