### ISSUE TITLE
Feeder Documentation - Updating Feeder Firmware

### ISSUE THREAD

**Issue by KC0D** [opulo-inc/feeder#27]
The instructions for updating the feeder firmware shows the use of an Arduino type USB to serial adapter with 6 pins.  The adapter like the one you have shown, has a jumper near the pins that sets the output voltage and output signal levels to 3.3V or 5V.  

The instructions should warn users to set the jumper to 3.3V before inserting it into the board.  Failure to do this could blow up the processor chip if it is set to output 5V

![image](https://github.com/opulo-inc/feeder/assets/91751383/ea6fcefd-a1a3-440d-a1fa-c07bee81949f)

**Comment by sphawes** [comment]
Thank you for the note @KC0D! That's a great point, we should absolutely add that.

This is the repo for the feeder source, but we have a separate repo for the documentation site. I've [remade this issue](https://github.com/opulo-inc/docs/issues/114) over there to track its completion, so I'll close this one. Thanks for logging this!
