### ISSUE TITLE
Fix Motor Drivers Bulk Capacitor Values (Rev.12 Branch)

### ISSUE THREAD

**Issue by FL140** [opulo-inc/feeder#29]
## Version Number
mobo Rev.12 Branch 20.05.2023 ~01:00 UTC

## Bugfix or Enhancement
Bugfix

## Description
It looks like placeholders (100nF) have been used for the motor driver bulk capacitors. 

## Suggested Solution
Replace the capacitors C18 & C20 with a reasonable size. Probably something in the range of 22uF.

**Comment by sphawes** [comment]
Hi @FL140! Thanks for the note! These values are not placeholders, they're following the recommended values from the DRV8837 datasheet:

<img width="695" alt="Screenshot 2023-05-24 at 4 55 32 PM" src="https://github.com/opulo-inc/feeder/assets/1865862/36f6d35a-c6b6-4db5-82fa-162acae684d5">

I don't think they're intended to act as bulk capacitors. We have a 470uF cap on the 10v rail that provides bulk capacitance for the VM pin on the drivers.

<img width="520" alt="Screenshot 2023-05-24 at 4 59 07 PM" src="https://github.com/opulo-inc/feeder/assets/1865862/ae85fd81-b17f-405e-a776-d3233f3f13d7">

Also, in an effort to not have duplicate issues, I'm going to close this issue and we can use [this issue](https://github.com/opulo-inc/feeder/issues/13) to sort out cap values.
