### ISSUE TITLE
Add eFuse protection to the +VDC(+24V) Feeder input pin

### ISSUE THREAD

**Issue by FL140** [opulo-inc/feeder#31]
## Version Number
Feeder Rev.12 Branch 20.05.2023 ~01:00 UTC

## Bugfix or Enhancement
Enhancement

## Description
There is no protection on the +VDC(+24V) supply pin.

## Suggested Solution
Add a proper eFuse IC the solution can solve:
- The current InRush Current problem.
- Short Circuits
- Over Currents
- Over Voltages
- Under Voltages
- Reverse Polarity
- ...
all in one IC.

**Comment by sphawes** [comment]
Hi @FL140! Thanks for the note! This is already something we're discussing in [this issue](https://github.com/opulo-inc/feeder/issues/13), so I'm going to close to prevent duplicates.
