### ISSUE TITLE
Rotate Board in PCB Editor by 180˚

### ISSUE THREAD

**Issue by FL140** [opulo-inc/feeder#32]
## Version Number
mobo Rev.12 Branch 20.05.2023 ~01:00 UTC

## Bugfix or Enhancement
Enhancement

## Description
The board is rotated by 180° in the PCB Editor. The Top is at the bottom and vice versa.

## Suggested Solution
Simple, rotate the whole Board in PCB Editor by 180˚.

**Comment by sphawes** [comment]
Hi @FL140! Thanks for the note! We actually keep it rotated because it allows KiKit to more easily panelize the board. Not too bad to just rotate it on your local copy if you prefer making edits and reviews that way!
