### ISSUE TITLE
Feeder frame nut counterbores

### ISSUE THREAD

**Issue by ashlynblack** [opulo-inc/feeder#43]
## Version Number
Have opened in FreeCAD 0.19 and 0.21

## Bugfix or Enhancement
Feeder frame

## Description
the counterbores / reliefs for the hex nuts are not present
![nut-bores](https://github.com/user-attachments/assets/02de2bf4-374d-4dc6-b211-1c5fe160b6f1)

**Comment by lucian151** [comment]
We now use self-tapping screws so nuts aren't needed!
