### ISSUE TITLE
Diffuser and fiducial should be panelized

### ISSUE THREAD

**Issue by qwertymodo** [opulo-inc/feeder#7]
Some manufacturers have issues producing very small individual boards like the diffuser and fiducial board.  Panelizing them with V-slots would alleviate that issue and help streamline manufacturing.

**Comment by sphawes** [comment]
This repo is meant to have the source design files for each board in the feeder, not panelized versions. If you're having a hard time getting them made, asking the board shop to panelize it themselves has worked well for us in the past! I've also been able to order both of these boards non-panelized from JLCPCB.
